src/main/java/com/bugsquashers/backend/image/domain/ReviewImage.java, src/main/java/com/bugsquashers/backend/movie/domain/Genre.java, src/main/java/com/bugsquashers/backend/movie/domain/Movie.java, src/main/java/com/bugsquashers/backend/movie/domain/MovieGenre.java, src/main/java/com/bugsquashers/backend/movie/domain/MovieGenreId.java, src/main/java/com/bugsquashers/backend/reservation/domain/Reservation.java, src/main/java/com/bugsquashers/backend/review/domain/Review.java, src/main/java/com/bugsquashers/backend/theater/domain/Theater.java, src/main/java/com/bugsquashers/backend/user/domain/RefreshToken.java, src/main/java/com/bugsquashers/backend/user/domain/User.java, src/main/java/com/bugsquashers/backend/user/domain/UserGenre.java, src/main/java/com/bugsquashers/backend/user/domain/UserGenreId.java
#1 
DB ERD를 기준으로 해당되는 도메인을 생성하였습니다.
자세한 사항은 이슈에 메모해둠
=> Feat: domain 생성

build.gradle, src/main/java/com/bugsquashers/backend/auth/config/SecurityConfig.java, src/main/java/com/bugsquashers/backend/auth/filter/BasicLoginFilter.java, src/main/java/com/bugsquashers/backend/auth/filter/JwtAuthenticationFilter.java, src/main/java/com/bugsquashers/backend/auth/jwt/JwtGenerator.java, src/main/java/com/bugsquashers/backend/auth/jwt/JwtRule.java, src/main/java/com/bugsquashers/backend/auth/jwt/JwtService.java, src/main/java/com/bugsquashers/backend/auth/jwt/TokenStatus.java, src/main/java/com/bugsquashers/backend/user/UserController.java, src/main/java/com/bugsquashers/backend/user/UserPrincipal.java, src/main/java/com/bugsquashers/backend/user/domain/User.java, src/main/java/com/bugsquashers/backend/user/dto/UserJoinRequest.java, src/main/java/com/bugsquashers/backend/user/dto/UserJoinResponse.java, src/main/java/com/bugsquashers/backend/user/repository/RefreshTokenRepository.java, src/main/java/com/bugsquashers/backend/user/repository/UserRepository.java, src/main/java/com/bugsquashers/backend/user/service/CustomUserDetailsService.java, src/main/java/com/bugsquashers/backend/user/service/UserService.java, src/main/java/com/bugsquashers/backend/util/GlobalExceptionHandler.java, src/main/java/com/bugsquashers/backend/util/response/ApiResponse.java, src/main/java/com/bugsquashers/backend/util/response/ErrorStatus.java, src/main/java/com/bugsquashers/backend/util/response/SuccessStatus.java
#6 
Spring Security 이용한 인증/인가 기능 구현
api 응답 통일을 위한 유틸까지 작성 완료함
=> feat: 인증/인가 기능 구현

build.gradle, src/main/java/com/bugsquashers/backend/movie/domain/Movie.java, src/main/java/com/bugsquashers/backend/user/UserController.java, src/main/java/com/bugsquashers/backend/user/dto/UserJoinRequest.java, src/main/java/com/bugsquashers/backend/util/OpenApiConfig.java, src/main/resources/application.properties
#8 
Swagger API Docs 자동화
http://localhost:8080/swagger-ui/index.html#/
=> feat: Swagger API Docs 자동화

src/main/java/com/bugsquashers/backend/admin/AdminController.java, src/main/java/com/bugsquashers/backend/admin/AdminService.java, src/main/java/com/bugsquashers/backend/auth/config/SecurityConfig.java, src/main/java/com/bugsquashers/backend/user/UserController.java, src/main/java/com/bugsquashers/backend/user/UserPrincipal.java, src/main/java/com/bugsquashers/backend/user/dto/UserInfoResponse.java, src/main/java/com/bugsquashers/backend/user/dto/UserInfoUpdateRequest.java, src/main/java/com/bugsquashers/backend/user/dto/UserPasswordUpdateRequest.java, src/main/java/com/bugsquashers/backend/user/service/UserService.java
=> feat: 회원 API

src/main/java/com/bugsquashers/backend/movie/MovieController.java, src/main/java/com/bugsquashers/backend/movie/domain/Genre.java, src/main/java/com/bugsquashers/backend/movie/domain/Movie.java, src/main/java/com/bugsquashers/backend/movie/domain/MovieGenre.java, src/main/java/com/bugsquashers/backend/movie/dto/GenreMoviesDto.java, src/main/java/com/bugsquashers/backend/movie/dto/GenreResponse.java, src/main/java/com/bugsquashers/backend/movie/dto/MovieDto.java, src/main/java/com/bugsquashers/backend/movie/repository/MovieRepository.java, src/main/java/com/bugsquashers/backend/movie/service/MovieService.java
=> feat: 영화 api 중간 PR

src/main/java/com/bugsquashers/backend/movie/MovieController.java, src/main/java/com/bugsquashers/backend/movie/dto/GenreMoviesDto.java, src/main/java/com/bugsquashers/backend/movie/dto/MovieDto.java, src/main/java/com/bugsquashers/backend/movie/repository/MovieRepository.java, src/main/java/com/bugsquashers/backend/movie/service/MovieService.java, src/main/java/com/bugsquashers/backend/util/GlobalExceptionHandler.java
=> Feat: 영화 및 장르 API

src/main/java/com/bugsquashers/backend/movie/MovieController.java, src/main/java/com/bugsquashers/backend/movie/dto/MovieDto2.java, src/main/java/com/bugsquashers/backend/movie/service/MovieService.java
#11 
영화 상세 보기 수정 (장르 별 영화와 dto 공유하던거 분리 / 로딩문제)
=> fix: 영화 상세 정보 수정(로딩) #11

src/main/java/com/bugsquashers/backend/movie/MovieController.java, src/main/java/com/bugsquashers/backend/movie/repository/MovieRepository.java, src/main/java/com/bugsquashers/backend/movie/service/MovieService.java
#11 
출력 사항(갯수 20개 제한 걸고, 안걸고) 오류 수정
=> fix: 장르별 출력 오류(갯수제한) 수정 #11

src/main/java/com/bugsquashers/backend/user/service/UserService.java
=> fix: 이메일 중복검사 조건 추가 #30

src/main/java/com/bugsquashers/backend/BackendApplication.java, src/main/java/com/bugsquashers/backend/reservation/ReservationController.java, src/main/java/com/bugsquashers/backend/reservation/ReservationRepository.java, src/main/java/com/bugsquashers/backend/reservation/domain/Reservation.java, src/main/java/com/bugsquashers/backend/reservation/domain/ReservationStatus.java, src/main/java/com/bugsquashers/backend/reservation/dto/GetAvailableTimesInDayResponse.java, src/main/java/com/bugsquashers/backend/reservation/dto/ReservationDetailsResponse.java, src/main/java/com/bugsquashers/backend/reservation/dto/ReservationRequest.java, src/main/java/com/bugsquashers/backend/reservation/service/ReservationService.java, src/main/java/com/bugsquashers/backend/reservation/service/ReservationStatusScheduler.java, src/main/java/com/bugsquashers/backend/theater/TheaterRepository.java, src/main/java/com/bugsquashers/backend/theater/TheaterService.java, src/main/java/com/bugsquashers/backend/user/service/UserService.java, src/main/java/com/bugsquashers/backend/util/GlobalExceptionHandler.java
=> feat: 예약 API 완성

src/main/java/com/bugsquashers/backend/auth/config/SecurityConfig.java, src/main/java/com/bugsquashers/backend/user/repository/UserRepository.java, src/main/java/com/bugsquashers/backend/user/service/UserService.java
#35
- 회원가입 시 전화번호 중복시 오류 예외처리
- 회원가입시 필요한 장르 api 인증 없이 사용 가능하도록 오픈
=> fix: 회원가입 예외처리 및 api 권한 오픈 

src/main/java/com/bugsquashers/backend/theater/TheaterController.java
=> feat: 상영관 id로 상세조회 #37

build.gradle, src/main/java/com/bugsquashers/backend/image/ImageService.java, src/main/java/com/bugsquashers/backend/review/domain/ReviewImage.java
=> feat: 이미지 업로드 서비스 #25

src/main/java/com/bugsquashers/backend/review/repository/ReviewRepository.java, src/main/java/com/bugsquashers/backend/review/service/ReviewService.java
#24 
예약 1개당 리뷰 1개만 작성 가능하도록 중복체크 추가
=> feat: 예약 1개당 리뷰 1개만 작성 가능하도록 중복체크 추가 #24

src/main/java/com/bugsquashers/backend/review/ReviewController.java, src/main/java/com/bugsquashers/backend/review/dto/ReviewListResponse.java, src/main/java/com/bugsquashers/backend/review/service/ReviewService.java
=> fix: 상영관 별 리뷰 목록에서 불필요한 정보 제거 #24

src/main/java/com/bugsquashers/backend/auth/jwt/JwtGenerator.java, src/main/java/com/bugsquashers/backend/reservation/ReservationController.java, src/main/java/com/bugsquashers/backend/reservation/dto/GetAvailableTimesInDayResponse.java, src/main/java/com/bugsquashers/backend/reservation/service/ReservationService.java, src/main/java/com/bugsquashers/backend/reservation/service/TimeSlotCalculationService.java
=> feat: 특정 날짜 예약 가능 시간 목록 응답 개선 #47

src/main/java/com/bugsquashers/backend/review/service/ReviewService.java
#24 
이용 완료한 예약에 대해서만 리뷰 남기도록 조건 추가 및 exception 수정
=> feat: 이용 완료한 예약에 대해서만 리뷰 남기도록 조건 추가 및 exception 수정 #24

src/main/java/com/bugsquashers/backend/reservation/domain/ReservationStatus.java, src/main/java/com/bugsquashers/backend/reservation/dto/ReservationDetailsResponse.java
=> fix: 예약 상태 응답 문구 개선

src/main/java/com/bugsquashers/backend/reservation/domain/ReservationStatus.java
=> fix: 누가 자꾸 바꿔달라고 하네요 그래서 띄워기 하나 추가를 했어요. 근데 자꾸 언급해달라는 관종 짓을 누군가가 하네요?

src/main/java/com/bugsquashers/backend/admin/AdminController.java, src/main/java/com/bugsquashers/backend/admin/AdminDto.java, src/main/java/com/bugsquashers/backend/admin/AdminService.java
=> feat: 예약조회

src/main/java/com/bugsquashers/backend/movie/MovieController.java, src/main/java/com/bugsquashers/backend/review/ReviewController.java
#11 , #54 
RequestMapping 수정, 설명 수정
=> fix: RequestMapping 수정, 설명 수정 #54

src/main/java/com/bugsquashers/backend/admin/AdminController.java, src/main/java/com/bugsquashers/backend/admin/AdminService.java, src/main/java/com/bugsquashers/backend/reservation/ReservationRepository.java, src/main/java/com/bugsquashers/backend/review/domain/ReviewImage.java, src/main/java/com/bugsquashers/backend/user/repository/UserRepository.java
=> feat:관리자 api #25

src/main/java/com/bugsquashers/backend/user/UserController.java, src/main/java/com/bugsquashers/backend/user/repository/UserRepository.java, src/main/java/com/bugsquashers/backend/user/service/UserService.java
=> feat: 로그인 페이지 아이디/비번 찾기 백

Dockerfile, appspec.yaml, scripts/install_dependencies.sh, scripts/start_server.sh, scripts/stop_server.sh
=> feat: aws 배포 #64
